import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/material-icons/material-icons.css'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'

import {
  // ClosePopup,
  // Dialog,
  // Loading,
  // Notify,
  // QAvatar,
  // QBar,
  QBtn,
  // QBtnToggle,
  // QCard,
  // QCardActions,
  // QCardSection,
  // QCheckbox,
  // QDialog,
  // QDrawer,
  // QExpansionItem,
  // QForm,
  // QHeader,
  // QIcon,
  // QImg,
  // QInput,
  // QItem,
  // QItemLabel,
  // QItemSection,
  // QLayout,
  // QLinearProgress,
  // QList,
  // QMenu,
  // QPage,
  // QPageContainer,
  // QScrollArea,
  // QSeparator,
  // QSpace,
  // QSplitter,
  // QToolbar,
  // QToolbarTitle,
  // QTooltip,
  Quasar,
  // Ripple,
} from 'quasar'
import Vue from 'vue'

Vue.use(Quasar, {
  components: {
    // QAvatar,
    // QBar,
    QBtn,
    // QBtnToggle,
    // QCard,
    // QCardActions,
    // QCardSection,
    // QCheckbox,
    // QDialog,
    // QDrawer,
    // QExpansionItem,
    // QForm,
    // QHeader,
    // QIcon,
    // QImg,
    // QInput,
    // QItem,
    // QItemLabel,
    // QItemSection,
    // QLayout,
    // QLinearProgress,
    // QList,
    // QMenu,
    // QPage,
    // QPageContainer,
    // QScrollArea,
    // QSeparator,
    // QSpace,
    // QSplitter,
    // QToolbar,
    // QToolbarTitle,
    // QTooltip,
  },
  config: {
    // notify: {},
    // loading: {},
  },
  directives: {
    // ClosePopup,
    // Ripple,
  },
  plugins: {
    // Dialog,
    // Loading,
    // Notify,
  },
})
